<a href="https://colab.research.google.com/github/chebbin/sqlite_database_operations/blob/main/code/sqlite_hw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Load in packages
import pandas as pd
import numpy as np
import sqlite3
from sqlalchemy import create_engine

In [4]:
# Import the transparency price dataset for stonybrook hospital
df = pd.read_csv('/content/stonybrook.csv')
df

,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
0,10004,"FINE NEEDLE ASPIRATION BIOPSY, EACH ADDITIONAL...",Outpatient,Line,718.67,718.67,2155.50,2155.50,2155.50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,2061.25,2061.25,87.02,4782.00,2308.44,2411.0,...,NaN,4782.0,NaN,NaN,3845.25,NaN,NaN,658.94,NaN,NaN
2,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Package,2061.25,2061.25,87.02,4782.00,2308.44,2411.0,...,NaN,4782.0,NaN,NaN,3845.25,NaN,NaN,658.94,NaN,NaN
3,10006,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,728.54,728.54,58.55,1761.25,909.90,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,2823.01,2823.01,446.28,6017.59,4219.31,4592.0,...,NaN,NaN,NaN,NaN,5127.00,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7705,30981203,R&B SICU 09W1 ICR PT-Z,NaN,NaN,12090.00,12090.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7706,30993018,R&B TICR 09W2 - PT-I,NaN,NaN,13590.00,13590.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7707,33500000,R&B REV PICU 11S2 PT-X,NaN,NaN,8165.00,8165.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7708,30333058,ROPH HOSP.OBSERVATION PT-T,NaN,NaN,8165.00,8165.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7709,30000004,SEMI-PRIVATE,NaN,NaN,8165.00,8165.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(7710, 57)

In [6]:
df.columns

Index(['Code', 'Description', 'Type', 'Package/Line_Level', 'Gross charge',
       'Discounted cash price', 'De-identified min contracted rate',
       'De-identified max contracted rate', 'Derived contracted rate',
       '1199-Commercial other', 'Aetna-Medicare Advantage HMO',
       'Aetna-Commercial HMO/POS', 'Aetna-Commercial PPO/Open Access',
       'Aetna-Commercial other', 'Empire Health-Commercial other',
       'Empire Health-Commercial PPO/Open Access',
       'BlueCross BlueShield-Commercial other',
       'Beacon Health-Commercial other', 'Carelon Health-Commercial other',
       'Cigna-Commercial PPO/Open Access', 'Cigna-Commercial other',
       'Cigna-Commercial HMO/POS', 'EH Facet-Commercial other',
       'EmblemHealth-Commercial PPO/Open Access',
       'EmblemHealth-Commercial other', 'EmblemHealth-Commercial HMO/POS',
       'EmblemHealth-Medicaid HMO', 'EmblemHealth-Medicare Advantage HMO',
       'Empire Health-Commercial HMO/POS',
       'Empire Health-Medicare Advantage HMO', 'Empire Health-Medicaid HMO',
       'Evernorth-Commercial other', 'Fidelis-Commercial other',
       'Fidelis-Medicare Advantage HMO', 'Fidelis-Medicaid HMO',
       'GHI-Commercial other', 'HealthFirst-Commercial other',
       'HealthFirst-Medicare Advantage HMO', 'HealthFirst-Medicaid HMO',
       'HealthPlus HP-Medicaid HMO', 'HealthPlus HP-Commercial other',
       'HealthPlus HP-Medicare Advantage HMO', 'Humana-Commercial other',
       'Humana-Commercial HMO/POS', 'Humana-Commercial PPO/Open Access',
       'Meritain Health-Commercial other', 'Molina-Commercial other',
       'Optum-Commercial other', 'Oxford-Commercial other',
       'Oxford-Commercial HMO/POS', 'Tricare-Commercial other',
       'United Healthcare-Commercial other',
       'United Healthcare-Medicare Advantage HMO',
       'United Healthcare-Commercial HMO/POS',
       'United Healthcare-Medicaid HMO',
       'United Healthcare-Commercial PPO/Open Access',
       'Veteran Family-Commercial other'],
      dtype='object')

In [7]:
# Remove white space from column names
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['Code', 'Description', 'Type', 'Package/Line_Level', 'Gross_charge',
       'Discounted_cash_price', 'De-identified_min_contracted_rate',
       'De-identified_max_contracted_rate', 'Derived_contracted_rate',
       '1199-Commercial_other', 'Aetna-Medicare_Advantage_HMO',
       'Aetna-Commercial_HMO/POS', 'Aetna-Commercial_PPO/Open_Access',
       'Aetna-Commercial_other', 'Empire_Health-Commercial_other',
       'Empire_Health-Commercial_PPO/Open_Access',
       'BlueCross_BlueShield-Commercial_other',
       'Beacon_Health-Commercial_other', 'Carelon_Health-Commercial_other',
       'Cigna-Commercial_PPO/Open_Access', 'Cigna-Commercial_other',
       'Cigna-Commercial_HMO/POS', 'EH_Facet-Commercial_other',
       'EmblemHealth-Commercial_PPO/Open_Access',
       'EmblemHealth-Commercial_other', 'EmblemHealth-Commercial_HMO/POS',
       'EmblemHealth-Medicaid_HMO', 'EmblemHealth-Medicare_Advantage_HMO',
       'Empire_Health-Commercial_HMO/POS',
       'Empire_Health-Medicare_Advantage_HMO', 'Empire_Health-Medicaid_HMO',
       'Evernorth-Commercial_other', 'Fidelis-Commercial_other',
       'Fidelis-Medicare_Advantage_HMO', 'Fidelis-Medicaid_HMO',
       'GHI-Commercial_other', 'HealthFirst-Commercial_other',
       'HealthFirst-Medicare_Advantage_HMO', 'HealthFirst-Medicaid_HMO',
       'HealthPlus_HP-Medicaid_HMO', 'HealthPlus_HP-Commercial_other',
       'HealthPlus_HP-Medicare_Advantage_HMO', 'Humana-Commercial_other',
       'Humana-Commercial_HMO/POS', 'Humana-Commercial_PPO/Open_Access',
       'Meritain_Health-Commercial_other', 'Molina-Commercial_other',
       'Optum-Commercial_other', 'Oxford-Commercial_other',
       'Oxford-Commercial_HMO/POS', 'Tricare-Commercial_other',
       'United_Healthcare-Commercial_other',
       'United_Healthcare-Medicare_Advantage_HMO',
       'United_Healthcare-Commercial_HMO/POS',
       'United_Healthcare-Medicaid_HMO',
       'United_Healthcare-Commercial_PPO/Open_Access',
       'Veteran_Family-Commercial_other'],
      dtype='object')

In [8]:
# Check the type of data in each column
df.dtypes

Code                                             object
Description                                      object
Type                                             object
Package/Line_Level                               object
Gross_charge                                    float64
Discounted_cash_price                           float64
De-identified_min_contracted_rate               float64
De-identified_max_contracted_rate               float64
Derived_contracted_rate                         float64
1199-Commercial_other                           float64
Aetna-Medicare_Advantage_HMO                    float64
Aetna-Commercial_HMO/POS                        float64
Aetna-Commercial_PPO/Open_Access                float64
Aetna-Commercial_other                          float64
Empire_Health-Commercial_other                  float64
Empire_Health-Commercial_PPO/Open_Access        float64
BlueCross_BlueShield-Commercial_other           float64
Beacon_Health-Commercial_other                  float64
Carelon_Health-Commercial_other                 float64
Cigna-Commercial_PPO/Open_Access                float64
Cigna-Commercial_other                          float64
Cigna-Commercial_HMO/POS                        float64
EH_Facet-Commercial_other                       float64
EmblemHealth-Commercial_PPO/Open_Access         float64
EmblemHealth-Commercial_other                   float64
EmblemHealth-Commercial_HMO/POS                 float64
EmblemHealth-Medicaid_HMO                       float64
EmblemHealth-Medicare_Advantage_HMO             float64
Empire_Health-Commercial_HMO/POS                float64
Empire_Health-Medicare_Advantage_HMO            float64
Empire_Health-Medicaid_HMO                      float64
Evernorth-Commercial_other                      float64
Fidelis-Commercial_other                        float64
Fidelis-Medicare_Advantage_HMO                  float64
Fidelis-Medicaid_HMO                            float64
GHI-Commercial_other                            float64
HealthFirst-Commercial_other                    float64
HealthFirst-Medicare_Advantage_HMO              float64
HealthFirst-Medicaid_HMO                        float64
HealthPlus_HP-Medicaid_HMO                      float64
HealthPlus_HP-Commercial_other                  float64
HealthPlus_HP-Medicare_Advantage_HMO            float64
Humana-Commercial_other                         float64
Humana-Commercial_HMO/POS                       float64
Humana-Commercial_PPO/Open_Access               float64
Meritain_Health-Commercial_other                float64
Molina-Commercial_other                         float64
Optum-Commercial_other                          float64
Oxford-Commercial_other                         float64
Oxford-Commercial_HMO/POS                       float64
Tricare-Commercial_other                        float64
United_Healthcare-Commercial_other              float64
United_Healthcare-Medicare_Advantage_HMO        float64
United_Healthcare-Commercial_HMO/POS            float64
United_Healthcare-Medicaid_HMO                  float64
United_Healthcare-Commercial_PPO/Open_Access    float64
Veteran_Family-Commercial_other                 float64
dtype: object

In [9]:
# Create a temporary and local database using SQLITE
conn = sqlite3.connect('health.db')
c = conn.cursor()

In [10]:
# Create a new table called Stonybrook with the health.db file
# that has three categorical columns and two numerical columns
c.execute('''CREATE TABLE Stonybrook
                (
                    [Code] text,
                    [Description] text,
                    [Type] text,
                    [Gross_charge] real,
                    [Derived_contracted_rate] real

                )''')

conn.commit()

In [11]:
## Confirm that the new table Stonybrook has been created within the database health.db

c.execute('''
SELECT name
FROM sqlite_master
WHERE type='table';
''')

for value in c.fetchall():
    print(value)

('Stonybrook',)

In [12]:
# Insert Data
sql_query = '''

INSERT INTO Stonybrook (
  'Code',
  'Description',
  'Type',
  'Gross_charge',
  'Derived_contracted_rate'
  )
values
  (
  '10004',
  'Fine needle aspiration biopsy',
  'Outpatient',
  718.67,
  2155.50
)

'''
print(sql_query)

INSERT INTO Stonybrook (
  'Code',
  'Description',
  'Type',
  'Gross_charge',
  'Derived_contracted_rate'
  )
values
  (
  '10004',
  'Fine needle aspiration biopsy',
  'Outpatient',
  718.67,
  2155.50
)

In [13]:
# Execute the query
c.execute(sql_query)
conn.commit()

In [14]:
# Create engine to connect to sqlite DB, then comment it out so the query can connect using pandas
# engine = create_engine('sqlite:///health.db')

In [15]:
# Check that the row was inserted using PANDAS and return the response as a dataframe
stonybrook = pd.read_sql("select * from Stonybrook", conn)
stonybrook

,Code,Description,Type,Gross_charge,Derived_contracted_rate
0,10004,Fine needle aspiration biopsy,Outpatient,718.67,2155.5

In [20]:
# Push the data from the transparencty price stonybrook dataset to the health.db database
df.to_sql('Stonybrook', conn, if_exists='replace')

7710

In [21]:
# Test
query = '''
  SELECT *
  FROM Stonybrook
  LIMIT 50;
'''

response = pd.read_sql(query, conn)
response

,index,Code,Description,Type,Package/Line_Level,Gross_charge,Discounted_cash_price,De-identified_min_contracted_rate,De-identified_max_contracted_rate,Derived_contracted_rate,...,Optum-Commercial_other,Oxford-Commercial_other,Oxford-Commercial_HMO/POS,Tricare-Commercial_other,United_Healthcare-Commercial_other,United_Healthcare-Medicare_Advantage_HMO,United_Healthcare-Commercial_HMO/POS,United_Healthcare-Medicaid_HMO,United_Healthcare-Commercial_PPO/Open_Access,Veteran_Family-Commercial_other
0,0,10004,"FINE NEEDLE ASPIRATION BIOPSY, EACH ADDITIONAL...",Outpatient,Line,718.67,718.67,2155.50,2155.50,2155.50,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
1,1,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,2061.25,2061.25,87.02,4782.00,2308.44,...,NaN,4782.00,None,NaN,3845.25,NaN,None,658.94,None,None
2,2,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Package,2061.25,2061.25,87.02,4782.00,2308.44,...,NaN,4782.00,None,NaN,3845.25,NaN,None,658.94,None,None
3,3,10006,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,728.54,728.54,58.55,1761.25,909.90,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
4,4,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,2823.01,2823.01,446.28,6017.59,4219.31,...,NaN,NaN,None,NaN,5127.00,NaN,None,NaN,None,None
5,5,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Package,2823.01,2823.01,446.28,6017.59,4219.31,...,NaN,NaN,None,NaN,5127.00,NaN,None,NaN,None,None
6,6,10010,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,588.00,588.00,2155.50,2155.50,2155.50,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
7,7,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Line,1566.78,1566.78,275.46,2265.50,1270.48,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
8,8,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Package,1566.78,1566.78,275.46,2265.50,1270.48,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
9,9,10030,DRAINAGE OF FLUID COLLECTION IN SOFT TISSUE US...,Outpatient,Line,2082.05,2082.05,152.66,4101.00,1663.85,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
10,10,10030,DRAINAGE OF FLUID COLLECTION IN SOFT TISSUE US...,Outpatient,Package,2212.17,2212.17,152.66,4101.00,1663.85,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
11,11,10035,PLACEMENT OF SOFT TISSUE LOCATING DEVICE USING...,Outpatient,Line,2919.67,2919.67,98.09,5127.00,2981.35,...,NaN,NaN,None,NaN,5127.00,NaN,None,NaN,None,None
12,12,10035,PLACEMENT OF SOFT TISSUE LOCATING DEVICE USING...,Outpatient,Package,3697.05,3697.05,98.09,5127.00,2981.35,...,NaN,NaN,None,NaN,5127.00,NaN,None,NaN,None,None
13,13,10060,SIMPLE OR SINGLE DRAINAGE OF SKIN ABSCESS,Outpatient,Line,968.07,968.07,100.00,4101.00,910.29,...,206.29,2529.00,None,206.29,1204.17,NaN,None,393.96,None,None
14,14,10060,SIMPLE OR SINGLE DRAINAGE OF SKIN ABSCESS,Outpatient,Package,968.07,968.07,100.00,4101.00,910.29,...,206.29,2529.00,None,206.29,1204.17,NaN,None,393.96,None,None
15,15,10061,COMPLICATED OR MULTIPLE DRAINAGE OF SKIN ABSCESS,Outpatient,Line,1457.10,1457.10,339.50,397.05,368.28,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
16,16,10061,COMPLICATED OR MULTIPLE DRAINAGE OF SKIN ABSCESS,Outpatient,Package,1457.10,1457.10,339.50,397.05,368.28,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
17,17,10080,SIMPLE DRAINAGE OF CYST OF TAILBONE,Outpatient,Line,1588.54,1588.54,100.00,2683.00,651.08,...,NaN,2683.00,None,NaN,922.00,NaN,None,380.71,None,None
18,18,10080,SIMPLE DRAINAGE OF CYST OF TAILBONE,Outpatient,Package,3876.06,3876.06,100.00,2683.00,651.08,...,NaN,2683.00,None,NaN,922.00,NaN,None,380.71,None,None
19,19,10081,COMPLICATED DRAINAGE OF CYST OF TAILBONE,Outpatient,Line,5716.50,5716.50,693.29,3756.00,2224.65,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
20,20,10081,COMPLICATED DRAINAGE OF CYST OF TAILBONE,Outpatient,Package,6115.17,6115.17,693.29,3756.00,2224.65,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
21,21,10120,"REMOVAL OF FOREIGN BODY FROM TISSUE, ACCESSED ...",Outpatient,Line,1727.16,1727.16,366.76,4782.00,1636.28,...,NaN,4782.00,None,NaN,3448.13,397.05,None,380.71,None,None
22,22,10120,"REMOVAL OF FOREIGN BODY FROM TISSUE, ACCESSED ...",Outpatient,Package,1727.16,1727.16,366.76,4782.00,1636.28,...,NaN,4782.00,None,NaN,3448.13,397.05,None,380.71,None,None
23,23,10121,"REMOVAL OF FOREIGN BODY FROM TISSUE, ACCESSED ...",Outpatient,Line,8447.67,8447.67,5494.79,5494.79,5494.79,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
24,24,10121,"REMOVAL OF FOREIGN BODY FROM TISSUE, ACCESSED ...",Outpatient,Package,8447.67,8447.67,5494.79,5494.79,5494.79,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
25,25,10140,DRAINAGE OF BLOOD OR FLUID ACCUMULATION,Outpatient,Line,5194.03,5194.03,686.74,6050.00,2677.26,...,NaN,NaN,None,NaN,1778.38,NaN,None,686.74,None,None
26,26,10140,DRAINAGE OF BLOOD OR FLUID ACCUMULATION,Outpatient,Package,5194.03,5194.03,686.74,6050.00,2677.26,...,NaN,NaN,None,NaN,1778.38,NaN,None,686.74,None,None
27,27,10160,"ASPIRATION OF ABSCESS, BLOOD, OR CYST",Outpatient,Line,1251.06,1251.06,195.00,6017.59,1937.51,...,NaN,3151.33,None,NaN,1597.04,NaN,None,421.71,None,None
28,28,10160,"ASPIRATION OF ABSCESS, BLOOD, OR CYST",Outpatient,Package,1251.06,1251.06,195.00,6017.59,1937.51,...,NaN,3151.33,None,NaN,1597.04,NaN,None,421.71,None,None
29,29,10180,COMPLEX DRAINAGE OF WOUND INFECTION AFTER SURGERY,Outpatient,Line,3233.67,3233.67,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
30,30,10180,COMPLEX DRAINAGE OF WOUND INFECTION AFTER SURGERY,Outpatient,Package,11308.29,11308.29,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
31,31,11010,REMOVAL OF FOREIGN MATERIAL FROM SKIN AND TISS...,Outpatient,Line,4815.33,4815.33,4101.00,4101.00,4101.00,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
32,32,11010,REMOVAL OF FOREIGN MATERIAL FROM SKIN AND TISS...,Outpatient,Package,8752.83,8752.83,4101.00,4101.00,4101.00,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
33,33,11042,"REMOVAL OF SKIN AND TISSUE, 20.0 SQ CM OR LESS",Outpatient,Line,3033.06,3033.06,791.79,4822.00,2728.46,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
34,34,11042,"REMOVAL OF SKIN AND TISSUE, 20.0 SQ CM OR LESS",Outpatient,Package,3033.06,3033.06,791.79,4822.00,2728.46,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
35,35,11043,"REMOVAL OF MUSCLE AND/OR TISSUE, 20.0 SQ CM OR...",Outpatient,Line,4109.66,4109.66,601.64,3649.08,1706.07,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
36,36,11043,"REMOVAL OF MUSCLE AND/OR TISSUE, 20.0 SQ CM OR...",Outpatient,Package,4109.66,4109.66,601.64,3649.08,1706.07,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
37,37,11044,"REMOVAL OF BONE, 20.0 SQ CM OR LESS",Outpatient,Line,3062.42,3062.42,740.60,4782.00,2232.53,...,NaN,4782.00,None,NaN,NaN,NaN,None,NaN,None,None
38,38,11044,"REMOVAL OF BONE, 20.0 SQ CM OR LESS",Outpatient,Package,3062.42,3062.42,740.60,4782.00,2232.53,...,NaN,4782.00,None,NaN,NaN,NaN,None,NaN,None,None
39,39,11045,"REMOVAL OF SKIN AND TISSUE, EACH ADDITIONAL 20...",Outpatient,Line,1106.41,1106.41,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
40,40,11046,"REMOVAL OF MUSCLE AND/OR TISSUE, EACH ADDITION...",Outpatient,Line,2631.60,2631.60,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
41,41,11047,"REMOVAL OF BONE, EACH ADDITIONAL 20.0 SQ CM OR...",Outpatient,Line,1224.00,1224.00,NaN,NaN,NaN,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
42,42,11102,"BIOPSY OF RELATED SKIN GROWTH, FIRST GROWTH",Outpatient,Line,539.84,539.84,2411.00,2411.00,2411.00,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
43,43,11102,"BIOPSY OF RELATED SKIN GROWTH, FIRST GROWTH",Outpatient,Package,976.84,976.84,2411.00,2411.00,2411.00,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
44,44,11103,"BIOPSY OF RELATED SKIN GROWTH, EACH ADDITIONAL...",Outpatient,Line,619.20,619.20,2411.00,2411.00,2411.00,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
45,45,11104,"PUNCH BIOPSY, FIRST SKIN GROWTH",Outpatient,Line,1017.57,1017.57,54.63,2375.00,1115.52,...,NaN,2375.00,None,NaN,NaN,NaN,None,678.22,None,None
46,46,11104,"PUNCH BIOPSY, FIRST SKIN GROWTH",Outpatient,Package,1454.57,1454.57,54.63,2375.00,1115.52,...,NaN,2375.00,None,NaN,NaN,NaN,None,678.22,None,None
47,47,11105,"PUNCH BIOPSY, EACH ADDITIONAL SKIN GROWTH",Outpatient,Line,731.13,731.13,29.97,29.97,29.97,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
48,48,11106,"INCISION BIOPSY, FIRST SKIN GROWTH",Outpatient,Line,1581.27,1581.27,758.90,2066.25,1412.58,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None
49,49,11106,"INCISION BIOPSY, FIRST SKIN GROWTH",Outpatient,Package,1581.27,1581.27,758.90,2066.25,1412.58,...,NaN,NaN,None,NaN,NaN,NaN,None,NaN,None,None